// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqvxyoxufokdqujcxpqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxdnh5b3h1Zm9rZHF1amN4cHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMDk3NjYsImV4cCI6MjA1Njc4NTc2Nn0.zkFFJeasXokty3vfon9ScxCgl-7emjFSTQWLl-K_h8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);